version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    restart: always
    tty: true
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./www:/www
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network

networks:
  network:
    driver: bridge
